### ISSUE TITLE
[WIP] Golang tools roadmap

### ISSUE THREAD

**Issue by lumjjb** [spdx/tools-golang#155]
2022 2H (v0.4.0)
- [ ] Core model
  - [ ] Mapping from 2.1/2 to core
  - [ ] Do deduplication of code
- [ ] 2.3 support
  - [ ] struct
  - [ ] functions
- [ ] Higher level helper function/libraries to use ([reference bom tool](https://github.com/spdx/tools-golang/issues/144), etc.)
  - [ ] base: here's how to interact with SPDX elements
  - [ ] context-specific: to work with container images, rpm, deb (will use base library)
  - [ ] Upstream use of tools-golang to bom tool
- [ ] Formats
  - [ ] rdfloader - RDF document saver
- [ ] Collect usage patterns
  - [ ] kubernetes-sig/bom
  - [ ] anchore/syft
  - [ ] aquasecurity/trivy
  - [ ] [opensbom-generator/spdx-sbom-generator](https://github.com/opensbom-generator/spdx-sbom-generator)
  - [ ] Organizations
    - [ ] Google (@lumjjb)
    - [ ] Chaingaurd (Adolfo)
    - [ ] VMWare (Rose)
    - [ ] Oracle (Nisha)
- [ ] Misc
  - [ ] https://github.com/spdx/tools-golang/pull/139
  - [ ] https://github.com/spdx/tools-golang/pull/153/
  - [ ] Expand tests for other OS's: see https://github.com/spdx/tools-golang/issues/117
  - [ ] OpenSSF Best Practices badge

2023+
- [ ] SPDX 3.0
- [ ] SBOMs for releases: see https://github.com/spdx/tools-golang/issues/118
- [ ] Collect usage patterns
  - [ ] License usage (@swinslow) - people may want to be able to reason about it as tree (ANDs of licenses), etc. Moving from simple strings to structured data. Figure out how to parse license grammar (pretty involved).
- [ ] Formats
  - [ ] xlsx

**Comment by lumjjb** [comment]
@swinslow @RishabhBhatnagar re-organized this to more realistic timelines and to prioritize a q4 release.

**Comment by ded1976** [comment]
> 2022 2H (v0.4.0)
> - [x] 2.3 support https://github.com/spdx/tools-golang/issues/156
>   - [x] struct
>   - [x] functions
> - [x] Misc
>   - [x] https://github.com/spdx/tools-golang/issues/139
>   - [x] https://github.com/spdx/tools-golang/issues/153 
> 
> 
> v0.5.0 (2023 Q1)
> - [x] Core model https://github.com/spdx/tools-golang/issues/152
>   - [x] Mapping from 2.1/2 to core
>   - [X] Do deduplication of code
>  -[x] Collect usage patterns for open source and org use (https://github.com/spdx/tools-golang/issues/157)
> - [x] Higher level helper function/libraries to use https://github.com/spdx/tools-golang/issues/144
>   - [x] base: here's how to interact with SPDX elements
>   - [x] context-specific: to work with container images, rpm, deb (will use base library)
>   - [x] Upstream use of tools-golang to bom tool
> 
> v0.5.1 (2023 Q2)
> - [x] Formats
>   - [x] https://github.com/spdx/tools-golang/issues/150
> - [x] Misc
>   - [x] https://github.com/spdx/tools-golang/issues/117
>   - [x] https://github.com/spdx/tools-golang/issues/140
>   - [x] https://github.com/spdx/tools-golang/issues/110 
> 
> v0.6.0 (2023 H2)
> - [x] SPDX 3.0
> - [x] SBOMs for releases: see https://github.com/spdx/tools-golang/issues/118
> - [x] Collect usage patterns
>   - [x] https://github.com/spdx/tools-golang/issues/158 License usage (@swinslow) - people may want to be able to reason about it as tree (ANDs of licenses), etc. Moving from simple strings to structured data. Figure out how to parse license grammar (pretty involved).
> - [x] Formats
>   - [x] #138
